source ~/.vam
call vam#ActivateAddons(['Auto_Pairs', 'YouCompleteMe','Syntastic','Tagbar','ctrlp','The_NERD_tree', 'rails', 'The_NERD_Commenter', 'vim-coffee-script', 'buffet', 'surround', 'fugitive', 'vim-multiple-cursors', 'github:mattn/emmet-vim', 'ag', 'sleuth', 'notes', 'rails', 'vim-ruby', 'textobj-rubyblock', 'textobj-user', 'matchit.zip', 'dbext', 'SQLUtilities', 'better-whitespace', 'Rubytest', 'github:danchoi/ri.vim', 'eunuch', 'Gundo', 'gruvbox', 'UltiSnips', 'vim-snippets', 'vim-airline', 'github:Konfekt/FastFold'], {'auto_install' : 1})
" 'neocomplcache','github:JazzCore/neocomplcache-ultisnips',
set runtimepath+=~/.vim/vim-addon-manager

" Theming
set background=dark    " Setting dark mode"
:colorscheme gruvbox

" Turn on mouse
set mouse=a
" Allows click events to span across the whole screen
if has('mouse_sgr')
  set ttymouse=sgr
endif

" Remaps
map <F6> :Bufferlist<CR>
nmap <F8> :TagbarToggle<CR>
nmap <F9> :NERDTreeToggle<CR>
nmap <a-p> :CtrlPBuffer
nmap <c-q> :bp \| bd#<CR>
nnoremap <F5> :GundoToggle<CR>
set pastetoggle=<F7>

" Indentation
filetype indent plugin on
set autoindent

" Reduce timeout for O
set timeout timeoutlen=3000 ttimeoutlen=100

" Whitespace
let g:strip_whitespace_on_save = 1

" Line numbering
set number
nnoremap <Leader>n :set number!<CR>
if(&relativenumber != 1)
  nnoremap <Leader>e :set relativenumber!<CR>
  set relativenumber
  autocmd InsertEnter * :set number norelativenumber
  autocmd InsertLeave * :set number relativenumber
endif

set omnifunc=syntaxcomplete#Complete

let g:AutoPairsFlyMode = 1
let g:AutoPairsShortcutBackInsert = '<C-l>'
set clipboard=unnamed
set rtp+=~/.fzf

autocmd Filetype gitcommit setlocal spell textwidth=72

" Folding
set foldmethod=syntax
set foldlevel=1

" Set up backups
set backup
silent !mkdir -p ~/.vim_backup/tmp/backups > /dev/null 2>&1
set backupdir=~/.vim/tmp/backups
set writebackup

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Better autocomplete for ruby
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1

" Nerdtree
let NERDTreeShowLineNumbers=1

" Ultisnips
let g:UltiSnipsExpandTrigger="<c-e>"
